### ISSUE TITLE
5 month a sleep

### ISSUE THREAD

**Issue by jihadismail8** [beyondcode/livewire-devtools#12]
this extention is dead ??? 5 months and no updates what so ever !! ?

**Comment by dsturm** [comment]
@jihadismail8 This is OS - so feel free to contribute to it. And secondly, I really doubt that you can say @mpociot has been asleep for the last five months....

**Comment by jihadismail8** [comment]
@dsturm  first : of course i did not mean  @mpociot  is a sleep , i know he is busy guy ,  second: why you toke it so personally ???  thirdly : no need to tell anybody on github if he can contribute to open source project or not , its obvious anybody can !! thirdly  i am trying to figure out if the project is still in development or it has  useless fundamentals   ( i never made an extension before , i do not know if  i should go deep in that or not )
