### ISSUE TITLE
Allow Livewire to disable devtools support

### ISSUE THREAD

**Issue by mpociot** [beyondcode/livewire-devtools#3]
Right now the devtools are always enabled, as soon as Livewire is detected.
Livewire should add a flag based on the APP_ENV to determine if devtool support should be enabled or not.
This requires a PR to Livewire.

**Comment by barryvdh** [comment]
But in that case you would disable the devtools on the client-side? Because then anyone could create a fork without that check anyways?

**Comment by mpociot** [comment]
Yeah that’s right - but that’s also how vue devtools work

**Comment by gtu-myowin** [comment]
Hi @mpociot, 

May I know why did you close this enhancement? I want this too and I didn't have @barryvdh comment in mind until I read it. Now I have that in mind but still I would hesitate to fork the repository, compile to to a extension or use it as a in development version to inspect someone's site until I am eager to know. Therefore, I think the feature should be added.

**Comment by yudhees** [comment]
How to disable livewire devtools when the project is in production.i am using livewire version 2
