### ISSUE TITLE
Could not load manifest on Linux Chromium

### ISSUE THREAD

**Issue by matsava** [beyondcode/livewire-devtools#5]
**Steps**
1. Download release source.zip
2. Unzip
3. Click "Load unpacked"
4. Select folder
5. Error 
```
Manifest file is missing or unreadable
Could not load manifest.
```
![2020-09-04_22-36](https://user-images.githubusercontent.com/7782312/92279153-606c4180-eeff-11ea-8ec2-5f6687baa16b.png)

**Comment by nuernbergerA** [comment]
Hey @matsava,

have you tried [chrome.zip](https://github.com/beyondcode/livewire-devtools/releases/download/0.1.0/chrome.zip) instead of source?

**Comment by matsava** [comment]
Yeah, I should pay more attention when reading the instructions :D Thanks!
