### ISSUE TITLE
Livewire not detected

### ISSUE THREAD

**Issue by tanthammar** [beyondcode/livewire-devtools#7]
The menu icon dropdown says that Livewire isn't detected.

![image](https://user-images.githubusercontent.com/21239634/92373815-2ec1c900-f0ff-11ea-9acd-a6f031116eaa.png)

All is working in the "Livewire" tab, in devtools (after clicking the refresh button)

+ I just want to say that I am very grateful that you released this extension !!!

**Comment by mpociot** [comment]
Does this happen on Livewire 1.x and 2.x?

**Comment by ju5t** [comment]
I get this on v2. ~~I'm not using a CDN, it's bundled in with Webpack, if that makes any difference.~~ I haven't checked if this is the case with v1. Let me know if I can get you any other data if that helps.

My Chrome version is 86.0.4240.80.

edit: not sure why I said it was bundled in with Webpack. That's Alpine. 🤦‍♂️

**Comment by Adityasingh63git** [comment]
sorry i don't know about this .

**Comment by tanthammar** [comment]
Yes it remains w Livewire v2.
