### ISSUE TITLE
HookManager.js Error - Referencing Unknown Hook

### ISSUE THREAD

**Issue by nickpoulos** [beyondcode/livewire-devtools#9]
I just installed the latest version of the extension (v0.1.0) in latest version of Chrome (Version 85.0.4183.121 (Official Build) (64-bit))

When I visit a Livewire page, the tab loads up, but I immediately get an error: 

```
HookManager.js:30 Uncaught Livewire: Referencing unknown hook: [responseReceived]
register @ HookManager.js:30
registerHook @ Store.js:116
value @ index.js:43
t.b @ backend.js:1
m @ backend.js:1
e @ VM125:1
emit @ VM125:1
(anonymous) @ VM143:1
setTimeout (async)
(anonymous) @ VM143:1
(anonymous) @ VM143:1
i @ detector.js:1
661 @ detector.js:1
t @ detector.js:1
(anonymous) @ detector.js:1
(anonymous) @ detector.js:1
```

The Livewire component I am testing with is as vanilla can be, so I am fairly certain this is an error within the extension.

**Comment by kefivitch** [comment]
i have the same issue on MS Edge

**Comment by mpociot** [comment]
Which Livewire version are you using?

**Comment by kamilkozak** [comment]
I have the same problem with version 2.2.9

**Comment by Adityasingh63git** [comment]
i am use chrome

**Comment by Adityasingh63git** [comment]
version 86.0.4240.80.

**Comment by pjadanowski** [comment]
same here

**Comment by nickpoulos** [comment]
I tried to use the latest release (0.1.0) of the extension again in a new project, got the same error.

Currently using Livewire v2.3 and Chrome 87.0.4280.67, again with a very basic component.

**Comment by pagegwood** [comment]
ditto

**Comment by brn-solutions** [comment]
I had the same issue and a further issue when the component emits an event, submitted a pull request #11, please have a look @mpociot, might help.
